version: "3.8"

volumes:
  go_build_cache:

services:
  go:
    container_name: go
    build: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - go_build_cache:/app/tmp
    working_dir: /app
    command: sh -c "go mod tidy && air"