volumes:
  go_build_cache:
  node_modules:

services:
  go:
    container_name: go
    build: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - go_build_cache:/app/tmp
    working_dir: /app
    command: sh -c "go mod tidy && air"
  web:
    container_name: web
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
      - node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "pnpm run dev"