// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {todo} from '../models';
import {context} from '../models';

export function Lists(arg1:number):Promise<Array<todo.List>>;

export function NewList(arg1:string):Promise<todo.List>;

export function NewTask(arg1:number,arg2:string,arg3:boolean,arg4:string,arg5:string,arg6:number):Promise<todo.Task>;

export function RemoveList(arg1:number):Promise<void>;

export function RemoveTask(arg1:number):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Tasks(arg1:number):Promise<Array<todo.Task>>;

export function UpdateList(arg1:todo.List):Promise<void>;

export function UpdateTask(arg1:todo.Task):Promise<void>;
