// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Lists(arg1) {
  return window['go']['todo']['Todo']['Lists'](arg1);
}

export function NewList(arg1) {
  return window['go']['todo']['Todo']['NewList'](arg1);
}

export function NewTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['todo']['Todo']['NewTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RemoveList(arg1) {
  return window['go']['todo']['Todo']['RemoveList'](arg1);
}

export function RemoveTask(arg1) {
  return window['go']['todo']['Todo']['RemoveTask'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['todo']['Todo']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['todo']['Todo']['Startup'](arg1);
}

export function Tasks(arg1) {
  return window['go']['todo']['Todo']['Tasks'](arg1);
}

export function UpdateList(arg1) {
  return window['go']['todo']['Todo']['UpdateList'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['todo']['Todo']['UpdateTask'](arg1);
}
